import uuid
from datetime import datetime, timedelta
from django.core.management.base import BaseCommand
from crm.models import Opportunity


class Command(BaseCommand):
    help = 'Seed the database with sample opportunities'

    def handle(self, *args, **options):
        now = datetime.utcnow()

        data = [
            {
                'id': str(uuid.uuid4()),
                'company_name': 'TechCorp Solutions',
                'contact_name': 'Alice Johnson',
                'contact_email': 'alice@techcorp.com',
                'opportunity_name': 'Enterprise Cloud Migration',
                'description': 'Full migration of on-premise infrastructure to AWS.',
                'estimated_value': 250000.0,
                'currency': 'USD',
                'stage': 'negotiation',
                'priority': 'high',
                'probability': 75.0,
                'owner': 'Carlos Ruiz',
                'next_follow_up_date': (now + timedelta(days=3)).strftime('%Y-%m-%d'),
                'last_interaction_summary': 'Discussed pricing tiers and SLA terms.',
                'ai_recommendation': 'Prepare final contract and schedule closing meeting.',
                'created_at': (now - timedelta(days=14)).strftime('%Y-%m-%d %H:%M:%S'),
                'updated_at': (now - timedelta(days=1)).strftime('%Y-%m-%d %H:%M:%S'),
                'is_active': True,
            },
            {
                'id': str(uuid.uuid4()),
                'company_name': 'GreenLeaf Analytics',
                'contact_name': 'Bob Martinez',
                'contact_email': 'bob@greenleaf.io',
                'opportunity_name': 'Data Platform Implementation',
                'description': 'Deploy analytics dashboard and data warehouse.',
                'estimated_value': 180000.0,
                'currency': 'USD',
                'stage': 'proposal',
                'priority': 'medium',
                'probability': 50.0,
                'owner': 'Diana Park',
                'next_follow_up_date': (now + timedelta(days=7)).strftime('%Y-%m-%d'),
                'last_interaction_summary': 'Presented the proposal; client requested minor changes.',
                'ai_recommendation': 'Address feedback and send revised proposal.',
                'created_at': (now - timedelta(days=30)).strftime('%Y-%m-%d %H:%M:%S'),
                'updated_at': (now - timedelta(days=5)).strftime('%Y-%m-%d %H:%M:%S'),
                'is_active': True,
            },
            {
                'id': str(uuid.uuid4()),
                'company_name': 'BlueOcean Retail',
                'contact_name': 'Carol Chen',
                'contact_email': 'carol@blueoceanretail.com',
                'opportunity_name': 'E-commerce Platform Upgrade',
                'description': 'Migrate from legacy e-commerce to headless Shopify.',
                'estimated_value': 320000.0,
                'currency': 'USD',
                'stage': 'qualification',
                'priority': 'critical',
                'probability': 30.0,
                'owner': 'Carlos Ruiz',
                'next_follow_up_date': (now + timedelta(days=1)).strftime('%Y-%m-%d'),
                'last_interaction_summary': 'Initial discovery call; high interest but budget concerns.',
                'ai_recommendation': 'Prepare ROI analysis to justify investment.',
                'created_at': (now - timedelta(days=7)).strftime('%Y-%m-%d %H:%M:%S'),
                'updated_at': (now - timedelta(days=2)).strftime('%Y-%m-%d %H:%M:%S'),
                'is_active': True,
            },
            {
                'id': str(uuid.uuid4()),
                'company_name': 'Sunrise Ventures',
                'contact_name': 'David Kim',
                'contact_email': 'david@sunrise.vc',
                'opportunity_name': 'Portfolio Management Tool',
                'description': 'Custom SaaS for tracking startup investments.',
                'estimated_value': 95000.0,
                'currency': 'USD',
                'stage': 'prospecting',
                'priority': 'low',
                'probability': 15.0,
                'owner': 'Diana Park',
                'next_follow_up_date': (now + timedelta(days=14)).strftime('%Y-%m-%d'),
                'last_interaction_summary': 'Cold outreach; interested in a demo.',
                'ai_recommendation': 'Schedule product demo and share case studies.',
                'created_at': (now - timedelta(days=2)).strftime('%Y-%m-%d %H:%M:%S'),
                'updated_at': (now - timedelta(days=2)).strftime('%Y-%m-%d %H:%M:%S'),
                'is_active': True,
            },
            {
                'id': str(uuid.uuid4()),
                'company_name': 'Pinnacle Health',
                'contact_name': 'Eva Larson',
                'contact_email': 'eva@pinnaclehealth.org',
                'opportunity_name': 'Patient Portal Integration',
                'description': 'Integrate patient portal with EHR system.',
                'estimated_value': 410000.0,
                'currency': 'USD',
                'stage': 'negotiation',
                'priority': 'high',
                'probability': 80.0,
                'owner': 'Carlos Ruiz',
                'next_follow_up_date': (now + timedelta(days=5)).strftime('%Y-%m-%d'),
                'last_interaction_summary': 'Final terms agreed pending legal review.',
                'ai_recommendation': 'Coordinate with legal team and finalize contract.',
                'created_at': (now - timedelta(days=60)).strftime('%Y-%m-%d %H:%M:%S'),
                'updated_at': (now - timedelta(days=1)).strftime('%Y-%m-%d %H:%M:%S'),
                'is_active': True,
            },
            {
                'id': str(uuid.uuid4()),
                'company_name': 'Apex Logistics',
                'contact_name': 'Frank Torres',
                'contact_email': 'frank@apexlogistics.com',
                'opportunity_name': 'Fleet Management System',
                'description': 'IoT-based fleet tracking and optimization platform.',
                'estimated_value': 150000.0,
                'currency': 'EUR',
                'stage': 'closed_won',
                'priority': 'medium',
                'probability': 100.0,
                'owner': 'Carlos Ruiz',
                'next_follow_up_date': '',
                'last_interaction_summary': 'Contract signed; onboarding scheduled.',
                'ai_recommendation': 'Begin implementation and assign project manager.',
                'created_at': (now - timedelta(days=90)).strftime('%Y-%m-%d %H:%M:%S'),
                'updated_at': (now - timedelta(days=10)).strftime('%Y-%m-%d %H:%M:%S'),
                'is_active': True,
            },
            {
                'id': str(uuid.uuid4()),
                'company_name': 'Nova Education',
                'contact_name': 'Grace Huang',
                'contact_email': 'grace@novaedu.edu',
                'opportunity_name': 'LMS Migration Project',
                'description': 'Migrate from Moodle to custom LMS solution.',
                'estimated_value': 200000.0,
                'currency': 'USD',
                'stage': 'closed_lost',
                'priority': 'low',
                'probability': 0.0,
                'owner': 'Diana Park',
                'next_follow_up_date': '',
                'last_interaction_summary': 'Client chose competitor solution.',
                'ai_recommendation': 'Analyze loss reasons and re-engage in 6 months.',
                'created_at': (now - timedelta(days=120)).strftime('%Y-%m-%d %H:%M:%S'),
                'updated_at': (now - timedelta(days=30)).strftime('%Y-%m-%d %H:%M:%S'),
                'is_active': False,
            },
            {
                'id': str(uuid.uuid4()),
                'company_name': 'Quantum Finance',
                'contact_name': 'Henry Ito',
                'contact_email': 'henry@quantumfin.com',
                'opportunity_name': 'Risk Analytics Engine',
                'description': 'Real-time risk assessment and reporting module.',
                'estimated_value': 275000.0,
                'currency': 'USD',
                'stage': 'proposal',
                'priority': 'high',
                'probability': 60.0,
                'owner': 'Carlos Ruiz',
                'next_follow_up_date': (now + timedelta(days=10)).strftime('%Y-%m-%d'),
                'last_interaction_summary': 'Technical demo completed; positive feedback.',
                'ai_recommendation': 'Provide pricing proposal and reference clients.',
                'created_at': (now - timedelta(days=45)).strftime('%Y-%m-%d %H:%M:%S'),
                'updated_at': (now - timedelta(days=3)).strftime('%Y-%m-%d %H:%M:%S'),
                'is_active': True,
            },
        ]

        for item in data:
            Opportunity.objects.update_or_create(id=item['id'], defaults=item)

        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {len(data)} opportunities'))
