# Generated by Django 5.1.2 on 2026-08-08 04:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("contact_name", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                ("opportunity_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("estimated_value", models.FloatField(default=0.0)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("Lead nuevo", "Lead nuevo"),
                            ("Contactado", "Contactado"),
                            ("Diagnóstico", "Diagnóstico"),
                            ("Propuesta enviada", "Propuesta enviada"),
                            ("Negociación", "Negociación"),
                            ("Ganado", "Ganado"),
                            ("Perdido", "Perdido"),
                        ],
                        default="Lead nuevo",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Baja", "Baja"),
                            ("Media", "Media"),
                            ("Alta", "Alta"),
                            ("Crítica", "Crítica"),
                        ],
                        default="Media",
                        max_length=15,
                    ),
                ),
                ("probability", models.IntegerField(default=0)),
                ("owner", models.CharField(blank=True, default="", max_length=255)),
                ("next_follow_up_date", models.DateField(blank=True, null=True)),
                ("last_interaction_summary", models.TextField(blank=True, default="")),
                ("ai_recommendation", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
