# Generated by Django 5.1.2 on 2026-07-28 20:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("contact_name", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                ("opportunity_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("estimated_value", models.FloatField(default=0.0)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("prospecting", "Prospecting"),
                            ("qualification", "Qualification"),
                            ("proposal", "Proposal"),
                            ("negotiation", "Negotiation"),
                            ("closed_won", "Closed Won"),
                            ("closed_lost", "Closed Lost"),
                        ],
                        default="prospecting",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("probability", models.FloatField(default=0.0)),
                ("owner", models.CharField(blank=True, default="", max_length=255)),
                (
                    "next_follow_up_date",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("last_interaction_summary", models.TextField(blank=True, default="")),
                ("ai_recommendation", models.TextField(blank=True, default="")),
                ("created_at", models.CharField(blank=True, default="", max_length=19)),
                ("updated_at", models.CharField(blank=True, default="", max_length=19)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
